#
# Makefile for the urbetter drivers
#
obj-$(CONFIG_BT_RDA_587X_MODULE_SUPPORT) += ut_bt_dev.o
obj-$(CONFIG_URBETTER_GSENEOR_MMA7660)   += mma7660.o
obj-$(CONFIG_URBETTER_REGWATCH)               += regwatch.o
obj-$(CONFIG_URBETTER_TOUCHSCREEN_FT5X0X)               += ft5x0x_ts.o