# Makefile for Linux samples code

#obj-$(CONFIG_SAMPLES)	+= kobject/ kprobes/ tracepoints/ trace_events/ \
#			   hw_breakpoint/ kfifo/ kdb/ hidraw/
obj-$(y)	+= kobject/ kprobes/ tracepoints/ trace_events/ \
			   hw_breakpoint/ kfifo/ kdb/ hidraw/
