#define REGWATCH_PHY_BASE	 0x10000000
#define REGWATCH_PHY_END	 0xFFFFFFFC

#define LPDDR1_BASE_ADDR		0x50000000
#define BOOT_FB_BASE_ADDR		(LPDDR1_BASE_ADDR   + 0x0EC00000)	/* 0x5EC00000 from Bootloader */
#define CFG_LCD_FBUFFER	BOOT_FB_BASE_ADDR		/*	(CFG_FASTBOOT_TRANSFER_BUFFER+CFG_FASTBOOT_TRANSFER_BUFFER_SIZE) //256M start 4d200000 */
#define FB_START_ADD CFG_LCD_FBUFFER

/* GPIO (Chapter 6) */
#define ELFIN_GPIO_BASE			0xE0200000
#define GPIO_BASE                       0x11000000
#define GPIO_LB_BASE                    0x11400000

#define GPM2CON_OFFSET 			0x2a0 
#define GPM2DAT_OFFSET 			0x2a4 
#define GPM2PUD_OFFSET 			0x2a8 
#define GPM2DRV_SR_OFFSET 		0x2aC 
#define GPM2CONPDN_OFFSET 		0x2b0 
#define GPM2PUDPDN_OFFSET 		0x2b4 

#define GPC0CON_OFFSET 			0x060 
#define GPC0DAT_OFFSET 			0x064 
#define GPC0PUD_OFFSET 			0x068 
#define GPC0DRV_SR_OFFSET 		0x06C 
#define GPC0CONPDN_OFFSET 		0x070 
#define GPC0PUDPDN_OFFSET 		0x074 

#define GPC1CON_OFFSET 			0x080 
#define GPC1DAT_OFFSET 			0x084 
#define GPC1PUD_OFFSET 			0x088 
#define GPC1DRV_SR_OFFSET 		0x08C 
#define GPC1CONPDN_OFFSET 		0x090 
#define GPC1PUDPDN_OFFSET 		0x094 

#define GPF0CON_OFFSET 			0x180 
#define GPF0DAT_OFFSET 			0x184 
#define GPF0PUD_OFFSET 			0x188 
#define GPF0DRV_SR_OFFSET 		0x18C 
#define GPF0CONPDN_OFFSET 		0x190 
#define GPF0PUDPDN_OFFSET 		0x194 

#define GPF1CON_OFFSET 			0x1a0 
#define GPF1DAT_OFFSET 			0x1a4 
#define GPF1PUD_OFFSET 			0x1a8 
#define GPF1DRV_SR_OFFSET 		0x1aC 
#define GPF1CONPDN_OFFSET 		0x1b0 
#define GPF1PUDPDN_OFFSET 		0x1b4 

#define GPF2CON_OFFSET 			0x1c0 
#define GPF2DAT_OFFSET 			0x1c4 
#define GPF2PUD_OFFSET 			0x1c8 
#define GPF2DRV_SR_OFFSET 		0x1cc 
#define GPF2CONPDN_OFFSET 		0x1d0 
#define GPF2PUDPDN_OFFSET 		0x1d4 

#define GPF3CON_OFFSET 			0x1e0 
#define GPF3DAT_OFFSET 			0x1e4 
#define GPF3PUD_OFFSET 			0x1e8 
#define GPF3DRV_SR_OFFSET 		0x1eC 
#define GPF3CONPDN_OFFSET 		0x1f0 
#define GPF3PUDPDN_OFFSET 		0x1f4 

#define GPM2CON				(GPIO_BASE + GPM2CON_OFFSET)	 
#define GPM2DAT				(GPIO_BASE + GPM2DAT_OFFSET)		 
#define GPM2PUD				(GPIO_BASE + GPM2PUD_OFFSET)		 
#define GPM2DRV				(GPIO_BASE + GPM2DRV_SR_OFFSET)
#define GPM2CONPDN			(GPIO_BASE + GPM2CONPDN_OFFSET)	 
#define GPM2PUDPDN			(GPIO_BASE + GPM2PUDPDN_OFFSET)	 

#define GPC0CON				(GPIO_LB_BASE + GPC0CON_OFFSET)	 
#define GPC0DAT				(GPIO_LB_BASE + GPC0DAT_OFFSET)		 
#define GPC0PUD				(GPIO_LB_BASE + GPC0PUD_OFFSET)		 
#define GPC0DRV				(GPIO_LB_BASE + GPC0DRV_SR_OFFSET)
#define GPC0CONPDN			(GPIO_LB_BASE + GPC0CONPDN_OFFSET)	 
#define GPC0PUDPDN			(GPIO_LB_BASE + GPC0PUDPDN_OFFSET)

#define GPC1CON				(GPIO_LB_BASE + GPC1CON_OFFSET) 
#define GPC1DAT				(GPIO_LB_BASE + GPC1DAT_OFFSET)		 
#define GPC1PUD				(GPIO_LB_BASE + GPC1PUD_OFFSET)		 
#define GPC1DRV				(GPIO_LB_BASE + GPC1DRV_SR_OFFSET)
#define GPC1CONPDN			(GPIO_LB_BASE + GPC1CONPDN_OFFSET)	 
#define GPC1PUDPDN			(GPIO_LB_BASE + GPC1PUDPDN_OFFSET)	

#define GPF0CON				(GPIO_LB_BASE + GPF0CON_OFFSET) 
#define GPF0DAT				(GPIO_LB_BASE + GPF0DAT_OFFSET)		 
#define GPF0PUD				(GPIO_LB_BASE + GPF0PUD_OFFSET)		 
#define GPF0DRV				(GPIO_LB_BASE + GPF0DRV_SR_OFFSET)
#define GPF0CONPDN			(GPIO_LB_BASE + GPF0CONPDN_OFFSET)	 
#define GPF0PUDPDN			(GPIO_LB_BASE + GPF0PUDPDN_OFFSET)
#define GPF1CON				(GPIO_LB_BASE + GPF1CON_OFFSET) 
#define GPF1DAT				(GPIO_LB_BASE + GPF1DAT_OFFSET)		 
#define GPF1PUD				(GPIO_LB_BASE + GPF1PUD_OFFSET)		 
#define GPF1DRV				(GPIO_LB_BASE + GPF1DRV_SR_OFFSET)
#define GPF1CONPDN			(GPIO_LB_BASE + GPF1CONPDN_OFFSET)	 
#define GPF1PUDPDN			(GPIO_LB_BASE + GPF1PUDPDN_OFFSET)	 
#define GPF2CON				(GPIO_LB_BASE + GPF2CON_OFFSET) 
#define GPF2DAT				(GPIO_LB_BASE + GPF2DAT_OFFSET)		 
#define GPF2PUD				(GPIO_LB_BASE + GPF2PUD_OFFSET)		 
#define GPF2DRV				(GPIO_LB_BASE + GPF2DRV_SR_OFFSET)	 
#define GPF2CONPDN			(GPIO_LB_BASE + GPF2CONPDN_OFFSET)	 
#define GPF2PUDPDN			(GPIO_LB_BASE + GPF2PUDPDN_OFFSET)	 
#define GPF3CON				(GPIO_LB_BASE + GPF3CON_OFFSET) 
#define GPF3DAT				(GPIO_LB_BASE + GPF3DAT_OFFSET)		 
#define GPF3PUD				(GPIO_LB_BASE + GPF3PUD_OFFSET)		 
#define GPF3DRV				(GPIO_LB_BASE + GPF3DRV_SR_OFFSET)
#define GPF3CONPDN			(GPIO_LB_BASE + GPF3CONPDN_OFFSET)	 
#define GPF3PUDPDN			(GPIO_LB_BASE + GPF3PUDPDN_OFFSET)


